//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseworkv5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SecondDBEntities : DbContext
    {
        public SecondDBEntities()
            : base("name=SecondDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrators> Administrators { get; set; }
        public virtual DbSet<BrigadeMembers> BrigadeMembers { get; set; }
        public virtual DbSet<Brigades> Brigades { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<HubStations> HubStations { get; set; }
        public virtual DbSet<Inspection> Inspection { get; set; }
        public virtual DbSet<Repair> Repair { get; set; }
        public virtual DbSet<Routs> Routs { get; set; }
        public virtual DbSet<TakenBackTickets> TakenBackTickets { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<TimeTable> TimeTable { get; set; }
        public virtual DbSet<Trains> Trains { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
