//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseworkv5
{
    using System;
    using System.Collections.Generic;
    
    public partial class HubStations
    {
        public int HubStationsId { get; set; }
        public string StationName { get; set; }
        public int RouteId { get; set; }
    
        public virtual Routs Routs { get; set; }
    }
}
