//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseworkv5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        public int InspectionId { get; set; }
        public int TrainId { get; set; }
        public string Inspection1 { get; set; }
        public Nullable<System.DateTime> DateOfInspection { get; set; }
    
        public virtual Trains Trains { get; set; }
    }
}
