//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseworkv5
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakenBackTickets
    {
        public int TakenBackTicketsId { get; set; }
        public int TicketId { get; set; }
        public string TakenBack { get; set; }
        public Nullable<System.DateTime> DateWhenTakenBack { get; set; }
    
        public virtual Tickets Tickets { get; set; }
    }
}
