//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseworkv5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tickets()
        {
            this.TakenBackTickets = new HashSet<TakenBackTickets>();
        }
    
        public int TicketId { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public Nullable<int> BuyerId { get; set; }
        public int PassageId { get; set; }
        public string SoldCHeck { get; set; }
        public string TimeOfSell { get; set; }
        public string Reservation { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TakenBackTickets> TakenBackTickets { get; set; }
        public virtual TimeTable TimeTable { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
